### ISSUE TITLE
MVP (Minimum Viable Product) (Tracking issue)

### ISSUE THREAD

**Issue by sgen** [SisuStake/Secret-Hackathon#4]
Create an MVP (Minumum Viable Product)

- [ ] Contracts
- [ ] UI
  - [ ] Design
    - [ ] Wireframes
    - [ ] ~~Hi Fidelity~~ (Skipping for Expediency)
  - [ ] Develop
    - [ ] Basic HTML/CSS Implementation
    - [ ] Integrate [SvelteKit](https://kit.svelte.dev/)
    - [ ] Integrate Contracts [via Secret.js](https://secretjs.scrt.network/)
    - [ ] Basic QA
